<?php

use Illuminate\Database\Seeder;

class JuegoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $juegos = json_decode('
        {
            "0":{"release_date":"2020-04-10","publishers":["Square Enix"],"developers":["Square Enix"],"platform":["PlayStation 4"],"description":"A spectacular reimagining of one of the most visionary games ever, FINAL FANTASY VII REMAKE rebuilds and expands the legendary RPG for today.\r\nThe first entry in a multi-part saga, delivering a level of depth inconceivable for the original. Mind-blowing story, unforgettable characters, epic battles and technical excellence collide.","id":438559,"name":"Final Fantasy VII Remake","deck":"A spectacular reimagining of one of the most visionary games ever, FINAL FANTASY VII REMAKE rebuilds and expands the legendary RPG for today.\r\nThe first entry in a multi-part saga, delivering a level of depth inconceivable for the original. Mind-blowing story, unforgettable characters, epic battles and technical excellence collide.","image":{"square_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_tiny\/1593\/15930215\/3546367-screen%20shot%202019-06-11%20at%203.04.46%20pm.png","screen_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/screen_tiny\/1593\/15930215\/3546367-screen%20shot%202019-06-11%20at%203.04.46%20pm.png","square_small":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_small\/1593\/15930215\/3546367-screen%20shot%202019-06-11%20at%203.04.46%20pm.png","original":"https:\/\/gamespot1.cbsistatic.com\/uploads\/original\/1593\/15930215\/3546367-screen%20shot%202019-06-11%20at%203.04.46%20pm.png"},"genres":["Action","RPG"],"themes":[],"franchises":[{"name":"Final Fantasy"}],"images_api_url":"https:\/\/www.gamespot.com\/api\/images\/?filter=association%3A5000-438559","reviews_api_url":"https:\/\/www.gamespot.com\/api\/reviews\/?filter=association%3A5000-438559","articles_api_url":"https:\/\/www.gamespot.com\/api\/articles\/?filter=association%3A5000-438559","videos_api_url":"https:\/\/www.gamespot.com\/api\/videos\/?filter=association%3A5000-438559","releases_api_url":"https:\/\/www.gamespot.com\/api\/releases\/?filter=association%3A5000-438559","site_detail_url":"https:\/\/www.gamespot.com\/final-fantasy-vii-remake\/"},
			"1":{"release_date":"2000-08-15","publishers":["SquareSoft","Square Enix","Square EA"],"developers":["SquareSoft"],"platform":["PlayStation"],"description":"Featuring a storyline developed by the creator of Chrono Trigger and Xenogears, Chrono Cross has been christened the &quot;Best RPG Creation&quot; by its development team. With multiple scenarios cast along a single story thread, and many different endings, each replay can result in an entirely new adventure. In addition, a brand new battle system makes combat smooth and innovative by introducing an element field system and combo system that gives the player unparalleled flexibility in their fighting options. The elimination of random battles also quickens the pace of the game, and places the choice of where to battle in the players hands. With character designs by a famed Japanese illustrator and music by the original Chrono Trigger composer, Chrono Cross features visuals and sounds that bring its magic to life.","id":655,"name":"Chrono Cross","deck":"Chrono Cross may not have had the largest budget, but it has the largest heart.","image":{"square_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_tiny\/mig\/0\/9\/3\/6\/2210936-box_ccross.png","screen_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/screen_tiny\/mig\/0\/9\/3\/6\/2210936-box_ccross.png","square_small":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_small\/mig\/0\/9\/3\/6\/2210936-box_ccross.png","original":"https:\/\/gamespot1.cbsistatic.com\/uploads\/original\/mig\/0\/9\/3\/6\/2210936-box_ccross.png"},"genres":["RPG"],"themes":[],"franchises":[{"name":"Chrono Trigger"}],"images_api_url":"https:\/\/www.gamespot.com\/api\/images\/?filter=association%3A5000-655","reviews_api_url":"https:\/\/www.gamespot.com\/api\/reviews\/?filter=association%3A5000-655","articles_api_url":"https:\/\/www.gamespot.com\/api\/articles\/?filter=association%3A5000-655","videos_api_url":"https:\/\/www.gamespot.com\/api\/videos\/?filter=association%3A5000-655","releases_api_url":"https:\/\/www.gamespot.com\/api\/releases\/?filter=association%3A5000-655","site_detail_url":"https:\/\/www.gamespot.com\/chrono-cross\/"},
			"2":{"release_date":"2015-09-01","publishers":["Konami"],"developers":["Kojima Productions","Moby Dick Studio","Konami"],"platform":["PlayStation 3","PlayStation 4","PC","Xbox 360","Xbox One"],"description":"Metal Gear Solid V: The Phantom Pain marks the first open-world adventure in the series.","id":151575,"name":"Metal Gear Solid V: The Phantom Pain","deck":"Metal Gear Solid V: The Phantom Pain marks the first open-world adventure in the series.","image":{"square_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_tiny\/1197\/11970954\/2868772-516v5qnvuvl.jpg","screen_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/screen_tiny\/1197\/11970954\/2868772-516v5qnvuvl.jpg","square_small":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_small\/1197\/11970954\/2868772-516v5qnvuvl.jpg","original":"https:\/\/gamespot1.cbsistatic.com\/uploads\/original\/1197\/11970954\/2868772-516v5qnvuvl.jpg"},"genres":["Action","Adventure"],"themes":[{"name":"Modern"}],"franchises":[{"name":"Metal Gear"}],"images_api_url":"https:\/\/www.gamespot.com\/api\/images\/?filter=association%3A5000-151575","reviews_api_url":"https:\/\/www.gamespot.com\/api\/reviews\/?filter=association%3A5000-151575","articles_api_url":"https:\/\/www.gamespot.com\/api\/articles\/?filter=association%3A5000-151575","videos_api_url":"https:\/\/www.gamespot.com\/api\/videos\/?filter=association%3A5000-151575","releases_api_url":"https:\/\/www.gamespot.com\/api\/releases\/?filter=association%3A5000-151575","site_detail_url":"https:\/\/www.gamespot.com\/metal-gear-solid-v-the-phantom-pain\/"},
			"3":{"release_date":"2015-05-18","publishers":["Warner Bros. Interactive Entertainment","CD Projekt RED S.A.","CD Projekt Red Studio","Spike Chunsoft","Bandai Namco Games"],"developers":["CD Projekt Red Studio","Saber Interactive","CD Projekt RED S.A."],"platform":["PC","Macintosh","Xbox One","PlayStation 4"],"description":"The Witcher 3: Wild Hunt is a story-driven, next-generation open world RPG game, set in a visually stunning fantasy universe, full of meaningful choices and impactful consequences. In The Witcher, you are a professional monster hunter, tasked with finding a child of prophecy in a vast open world rich with merchant cities, dangerous mountain passes, and forgotten caverns to explore.","id":167462,"name":"The Witcher 3: Wild Hunt","deck":"The Witcher 3: Wild Hunt is a story-driven, next-generation open world RPG game, set in a visually stunning fantasy universe, full of meaningful choices and impactful consequences. In The Witcher, you are a professional monster hunter, tasked with finding a child of prophecy in a vast open world rich with merchant cities, dangerous mountain passes, and forgotten caverns to explore.","image":{"square_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_tiny\/1197\/11970954\/2847691-2568037-91v3ozkg-ml._sl1500_.jpg","screen_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/screen_tiny\/1197\/11970954\/2847691-2568037-91v3ozkg-ml._sl1500_.jpg","square_small":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_small\/1197\/11970954\/2847691-2568037-91v3ozkg-ml._sl1500_.jpg","original":"https:\/\/gamespot1.cbsistatic.com\/uploads\/original\/1197\/11970954\/2847691-2568037-91v3ozkg-ml._sl1500_.jpg"},"genres":["Action","RPG"],"themes":[],"franchises":[{"name":"The Witcher"}],"images_api_url":"https:\/\/www.gamespot.com\/api\/images\/?filter=association%3A5000-167462","reviews_api_url":"https:\/\/www.gamespot.com\/api\/reviews\/?filter=association%3A5000-167462","articles_api_url":"https:\/\/www.gamespot.com\/api\/articles\/?filter=association%3A5000-167462","videos_api_url":"https:\/\/www.gamespot.com\/api\/videos\/?filter=association%3A5000-167462","releases_api_url":"https:\/\/www.gamespot.com\/api\/releases\/?filter=association%3A5000-167462","site_detail_url":"https:\/\/www.gamespot.com\/the-witcher-3-wild-hunt\/"},
			"4":{"release_date":"2017-03-03","publishers":["Nintendo"],"developers":["Nintendo"],"platform":["Wii U","Nintendo Switch"],"description":"The Legend of Zelda for the Nintendo Wii U is embracing an open-world design and  will be returning to the series roots.","id":107502,"name":"The Legend of Zelda: Breath of the Wild","deck":"The Legend of Zelda for the Nintendo Wii U is embracing an open-world design and  will be returning to the series roots.","image":{"square_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_tiny\/1197\/11970954\/3181241-ig-lozbreathofthewildrelease-20170112.jpg","screen_tiny":"https:\/\/gamespot1.cbsistatic.com\/uploads\/screen_tiny\/1197\/11970954\/3181241-ig-lozbreathofthewildrelease-20170112.jpg","square_small":"https:\/\/gamespot1.cbsistatic.com\/uploads\/square_small\/1197\/11970954\/3181241-ig-lozbreathofthewildrelease-20170112.jpg","original":"https:\/\/gamespot1.cbsistatic.com\/uploads\/original\/1197\/11970954\/3181241-ig-lozbreathofthewildrelease-20170112.jpg"},"genres":["Action","Adventure"],"themes":[{"name":"Fantasy"}],"franchises":[{"name":"Legend of Zelda"}],"images_api_url":"https:\/\/www.gamespot.com\/api\/images\/?filter=association%3A5000-107502","reviews_api_url":"https:\/\/www.gamespot.com\/api\/reviews\/?filter=association%3A5000-107502","articles_api_url":"https:\/\/www.gamespot.com\/api\/articles\/?filter=association%3A5000-107502","videos_api_url":"https:\/\/www.gamespot.com\/api\/videos\/?filter=association%3A5000-107502","releases_api_url":"https:\/\/www.gamespot.com\/api\/releases\/?filter=association%3A5000-107502","site_detail_url":"https:\/\/www.gamespot.com\/the-legend-of-zelda-breath-of-the-wild\/"}
        }
        ');

        foreach (range(0, 4) as $i) {
            DB::table('juego')->insert([
                'nombre' => $juegos->{"$i"}->{"name"},
                'imagen' => "$i",   //esta imagen debe ser buscada en la tabla de imágenes.
                'genero' => json_encode($juegos->{"$i"}->{"genres"}),
                'fecha_lanzamiento' => $juegos->{"$i"}->{"release_date"},
                'descripcion'=> $juegos->{"$i"}->{"description"},
                'plataforma'=> json_encode($juegos->{"$i"}->{"platform"}),
                'editor'=> json_encode($juegos->{"$i"}->{"publishers"}),
                'desarrollador'=> json_encode($juegos->{"$i"}->{"developers"})
            ]);
        }
    }
}
